"""views

Revision ID: 0c897e9399a9
Revises: 8cad1973204c
Create Date: 2024-01-08 09:55:31.744014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c897e9399a9'
down_revision: Union[str, None] = '8cad1973204c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.run_ddl_script('2024_01_08_0955_last_month_orders_0c897e9399a9.sql')
    op.run_ddl_script('2024_01_08_0955_order_details_0c897e9399a9.sql')
    op.run_ddl_script('2024_01_08_0955_best_customer_0c897e9399a9.sql')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP VIEW IF EXISTS best_customer;')
    op.execute('DROP VIEW IF EXISTS order_details;')
    op.execute('DROP VIEW IF EXISTS last_month_orders;')
    # ### end Alembic commands ###
