"""customer_info

Revision ID: 060d60b5c278
Revises: af80846764cd
Create Date: 2024-01-08 10:45:36.026271

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "060d60b5c278"
down_revision: Union[str, None] = "af80846764cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_info_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "customer_info_customer_info_id_fk",
            "customer_info",
            ["customer_info_id"],
            ["customer_info_id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("customer_phone")
        batch_op.drop_column("customer_details_id")

    op.run_ddl_script("2024_01_08_1045_order_details_060d60b5c278.sql")
    op.run_ddl_script("2024_01_08_1045_customer_details_060d60b5c278.sql")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS customer_details;")
    op.run_ddl_script("2024_01_08_1016_order_details_af80846764cd.sql")
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_details_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("customer_phone", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("customer_info_customer_info_id_fk", type_="foreignkey")
        batch_op.drop_column("customer_info_id")

    # ### end Alembic commands ###
