"""product_prices

Revision ID: af80846764cd
Revises: 0c897e9399a9
Create Date: 2024-01-08 10:16:22.995715

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af80846764cd"
down_revision: Union[str, None] = "0c897e9399a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products_orders", sa.Column("price", sa.Integer(), nullable=True))
    op.run_ddl_script("2024_01_08_1016_order_details_af80846764cd.sql")
    op.run_ddl_script("2024_01_08_1016_best_customer_af80846764cd.sql")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.run_ddl_script("2024_01_08_0955_best_customer_0c897e9399a9.sql")
    op.run_ddl_script("2024_01_08_0955_order_details_0c897e9399a9.sql")
    op.drop_column("products_orders", "price")
    # ### end Alembic commands ###
